{
  "_info": [
    {
      "func_args": {
        "logs_index": 3
      },
      "test_file": "_private/test_core.py",
      "test_name": "test_core"
    }
  ],
  "_json": "\u29bf 2023-01-31 06:16:00.911331-05:00 ERROR   error-level log      record: \n{'elapsed': {'repr': '0:00:00.341591', 'seconds': 0.341591}, 'exception': None, \n'extra': {}, 'file': {'name': 'dodo.py', 'path': \n'/Users/kyleking/Developer/packages/tail-jsonl/dodo.py'}, 'function': \n'<module>', 'level': {'icon': '\u274c', 'no': 40}, 'line': 34, 'module': 'dodo', \n'name': 'dodo', 'process': {'id': 16268, 'name': 'MainProcess'}, 'thread': \n{'id': 8821244160, 'name': 'MainThread'}, 'time': {'timestamp': \n1675160160.911331}}\n \u221f text: 2023-01-31 06:16:00.911 | ERROR    | dodo:<module>:34 - error-level log\n\n"
}
