{
  "_info": [
    {
      "func_args": {
        "logs_index": 3
      },
      "test_file": "_private/test_core.py",
      "test_name": "test_core"
    }
  ],
  "_json": "2023-01-31 06:16:00.911331-05:00 [ERROR  ] error-level log record={'elapsed': {'repr': '0:00:00.341591', 'seconds': \n0.341591}, 'exception': None, 'extra': {}, 'file': {'name': 'dodo.py', 'path': \n'/Users/kyleking/Developer/packages/tail-jsonl/dodo.py'}, 'function': '<module>', 'level': {'icon': '\u274c', 'no': 40}, \n'line': 34, 'module': 'dodo', 'name': 'dodo', 'process': {'id': 16268, 'name': 'MainProcess'}, 'thread': {'id': \n8821244160, 'name': 'MainThread'}, 'time': {'timestamp': 1675160160.911331}}\n \u221f text: 2023-01-31 06:16:00.911 | ERROR    | dodo:<module>:34 - error-level log\n\n"
}
